export const intentionQuotes = [
  "Begin with the task that makes the rest of the day lighter.",
  "Protect the first hour; it teaches the rest of the day how to behave.",
  "Small focus, repeated honestly, becomes momentum.",
  "Do the next clear thing before chasing the next interesting thing.",
  "Attention is easier to keep when you give it a name.",
  "The work does not need drama. It needs a clean start.",
  "Choose one useful direction and let the noise wait outside.",
  "A calmer pace can still be a serious pace.",
  "Finish one loop before opening another.",
  "Make the important thing visible enough that it can pull you back.",
  "The day improves when your first promise is small and kept.",
  "Focus is not force. It is returning without argument.",
  "Give your best minutes to something that can compound.",
  "Start before you feel perfectly ready; clarity often follows motion.",
  "A named intention turns vague effort into a real appointment.",
  "Let the timer hold the boundary so your mind can hold the work.",
  "Choose progress you can recognize by evening.",
  "One honest block of attention is better than ten restless tabs.",
  "Move the day by inches, not by panic.",
  "Put your attention where tomorrow will thank you.",
  "A good session begins with knowing what counts as enough.",
  "Keep the work surface simple and the promise specific.",
  "The easiest distraction is the one you never invite in.",
  "Make room for depth before the day fills itself.",
  "Start with the thing you would be relieved to have finished.",
]

export const usefulRules = [
  "If you can name what you're about to do, start the timer. If you can't, pause for ten seconds.",
  "When a tab turns into a trail, switch the activity to Open time.",
  "If the timer name feels vague, rename the activity before continuing.",
  "Start one timer only. Let switching timers be a conscious context switch.",
  "When you finish a task, stop the timer before checking anything else.",
  "Use Intentional time for work you would defend at the end of the day.",
  "Use Open time for browsing, exploring, resting, and unscheduled loops.",
  "If you are avoiding a task, start a five-minute intentional block anyway.",
  "When Social Media starts running, set a smaller budget than feels comfortable.",
  "Reset a timer only when the record is genuinely wrong, not when it is inconvenient.",
  "If an activity exceeds its budget twice, lower the friction before judging yourself.",
  "Name the outcome, not just the category: write, review, learn, clean, ship.",
  "After every long Open-time block, choose one Intentional block next.",
  "If you switch tasks more than three times in ten minutes, pause and pick one.",
  "Let entertainment be recorded without guilt; the point is visibility.",
  "Do not optimize the ledger while avoiding the work it is tracking.",
  "If a task matters, give it a timer before giving it your inbox.",
  "End the session when the intention is met, not when attention collapses.",
  "Use the budget as a nudge, not a verdict.",
  "The best category is the one you will actually use consistently.",
  "When the day feels scattered, record the next ten minutes honestly.",
  "Open time is allowed; hidden time is what makes the day hard to read.",
  "If the timer is running, the screen should match the activity.",
  "Before adding a new activity, ask whether an existing one can be renamed.",
  "Review the balance as feedback, not as a score.",
]
